### PR TITLE
Express setup

### PR DESCRIPTION
**Pull request by eprager**
**Setup project to run with express.js**
Changes were made to the package.json files to rename to project-three.  
index.js (first draft developed by Kinza) was re-added to the project and incorporated through a new connection to index.js and a modified file structure to mirror the typical express.js file structure.  
Next, Alison will be modifying links between files so the CSS and JavaScript is properly connected to the HTML files.

**Update README with instructions to run the express node project**

### CODE REVIEW

**Review by missamcdonald — DISMISSED** [review]
Approved!

**Review by khaque1 — APPROVED** [review]
Looks good!

**Review by missamcdonald — APPROVED** [review]
Looks good, thank you!

**Review by missamcdonald — APPROVED** [review]
Sorry, approved this twice!

**Review by SnehaRajulapally — APPROVED** [review]

**Pull request merged**
