### PR TITLE
Changed file paths to reflect new folder structure.

### PR DESCRIPTION
**Pull request by missamcdonald**

### CODE REVIEW

**Review by SnehaRajulapally — APPROVED** [review]

**Comment by eprager** [comment]
In search.js, is this path correct? `window.location.href = "../public/results.html";`
I am wondering if the public part is needed or if it should be `../results.html`
It looks like that's what you had in the first commit.
@missamcdonald

**Comment by missamcdonald** [comment]
I tried that way and got an error saying page not found. It made no sense but when I added “public” it worked.

**Comment by eprager** [comment]
Okay!

**Review by eprager — APPROVED** [review]

**Review by khaque1 — APPROVED** [review]
Thanks!

**Pull request merged**
