### PR TITLE
README and JSDoc updates

### PR DESCRIPTION
**Pull request by eprager**
This is the final update to the beta release documentation (!) with minor updates to both readmes, as well as a runthrough of JSDocs.
- line breaks in the repo readme
- image paths work in the jsdoc readme now
- JSDocs changes also from recent PRs

Additional commit to comment out console messages for release

### CODE REVIEW

**Review by missamcdonald — DISMISSED** [review]
Looks good!

**Review by SnehaRajulapally — DISMISSED** [review]

**Review by SnehaRajulapally — APPROVED** [review]
Looks good!

**Review by khaque1 — APPROVED** [review]
Great!

**Review by missamcdonald — APPROVED** [review]
Looks good!

**Pull request merged**
